### ISSUE TITLE
Downloading data from Fluke 287

### ISSUE THREAD

**Issue by tbechtel** [wizkers/wizkers#1]
I can connect, and read remotely with no problems.  And I can see the number of measurements recorded locally on the Fluke, but I can't seem to transfer them from the Fluke to my laptop.  Is this possible?

**Comment by elafargue** [comment]
You are correct : I have not finalized log downloads on the Chrome app. It
is coming up though!

**Comment by tbechtel** [comment]
Wow, thanks for the speedy reply.  It is a fantastic app!
And will be even better when transfer is possible.
Thanks.
Tim

**Comment by elafargue** [comment]
Thanks Tim. I'm currently traveling - and without my DMM, believe it or not ;) - but I'll get to it as soon as I'm back. In the mean time, you can download trendlogs when running Wizkers as a nodeJS app - see wizkers.io for details on how to do this, it is very straightforward.

**Comment by elafargue** [comment]
Just pushed Wizkers 0.9.14 to the Chrome app store, give it an hour and update the app (check in the "About" menu that you are really running 0.9.14) and let me know if you can download your trendlogs!

**Comment by tbechtel** [comment]
Excellent!
Will do this morning.
Thanks,
Tim

**Comment by elafargue** [comment]
Hey Tim, did the update work for you? I need to improve user experience with the display of all log 'cards' : you can scroll, which is not obvious at first.

**Comment by tbechtel** [comment]
Edouard,
I am not computer savvy.  It took me a day to figure out that I needed to
uninstall, then re-install to get version 9.14.  But, now I have it, and it
works great!
I am in the field in a\Austria collecting data using the Fluke 287, and
just got back to our rented cabin, and dumped a week's worth of
measurements.  Fantastic!
Thank you.
I am going to go leave super-positive feedback.
Tim

On Tue, Jul 14, 2015 at 11:45 AM, Edouard Lafargue <notifications@github.com

**Comment by elafargue** [comment]
That's great news, thanks for your feedback! Google Chrome's update
system is a bit frustrating: new versions always end up downloading
automatically to your computer, but you never know when they will get there.

   Glad to hear it worked well for you!

**Comment by elafargue** [comment]
Closing after positing feedback from @tbechtel , thanks!
